---
name: "Connor Brennan"
position: ""
address: "Perelman School of Medicine, University of Pennsylvania"
www: sharsnik2.github.io/website/
email: brenco@pennmedicine.upenn.edu
github: sharsnik2
orcid: 0000-0002-5329-7720
aboutme: ""
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::moderncv:
    theme: classic
---

```{r eval=FALSE, include=FALSE}
# Remember to spell check!!
data_files <- list.files(here("data"), pattern = ".csv", full.names = TRUE)
#spelling::spell_check_files(c("cv_vitae.Rmd", data_files))
```

```{r eval=FALSE, include=FALSE}
# To update CV on my website, run the following code in the console:
rmarkdown::render("cv_vitae.Rmd", output_file = "~/cv.pdf")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(lubridate)
library(here)
library(readxl)
library(glue)
library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("here", "here")
#setwd("E:/Git/cv_vitae")
```

```{r experience, inclue=FALSE}
jobs.raw <- read_csv(here::here("data", "jobs.csv"))
jobs <-
  jobs.raw %>% 
  fill(Start, End, What, With, Where, Tag) %>%  
  mutate(Start = mdy(Start),
         End = mdy(End)) %>% 
  mutate(When = case_when(
    is.na(End) ~ glue("{year(Start)}--Present") %>% as.character(),
    year(Start) == year(End) ~ year(End) %>% as.character(),
    TRUE ~ glue("{year(Start)}--{year(End)}") %>% as.character()
  )) %>% 
  mutate(End = if_else(is.na(End), today() + years(2), End)) #if no end date specified, set it to two years from now for sorting purposes, i.e. so jobs I'm still doing show up at top.
```

```{r presentations, include=FALSE}
presentations.raw <- read_csv(here("data", "presentations.csv"))
presentations <- 
  presentations.raw %>% 
  mutate(When = mdy(When)) %>% 
  filter(When < today()) #exclude upcoming talks
```

```{r prof-devel, include=FALSE}
development.raw <- read_csv(here("data", "professional development.csv"))
development <- 
  development.raw %>% 
  mutate(date = mdy(date))
```

```{r awards, include=FALSE}
awards.raw <- read_csv(here("data", "awards and grants.csv"))
awards <- awards.raw %>% 
  mutate(date = mdy(date)) %>% 
  arrange(desc(date))
```

```{r edu, include=FALSE}
edu.raw <- read_csv(here("data", "education.csv"))
edu <-
  edu.raw %>% 
  mutate(pi = if_else(!is.na(pi), glue("PI: {pi}"), as.character(NA)),
         dissertation = glue("\\textbf{[dissertation]}", .open = "[", .close = "]")) %>% 
  gather( pi, key = "whytype", value = "why")
edu = edu %>% filter(degree != "N/A") 
edu["why"]
```
```{r outreach}
outreach.raw <- read_csv(here("data", "outreach.csv"))
outreach <- outreach.raw %>% mutate(sortdate = mdy(sortdate))
```


# Education 


```{r}
detailed_entries(edu, 
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = location,
                 with = university,
                 why = why,
                 .protect = FALSE)
```

# Publications

<!-- ^\*^ indicates undergraduate mentee author   -->

```{r publications}
pubs = scholar::get_publications("asa20tUAAAAJ", flush = TRUE) %>%
  mutate(author = as.character(author))


pubs %>%
  filter(year != 2020) %>%
  # in review
  dplyr::add_row(
  title = "Topological Models of Neural Population Dynamics are Predictive, Interpretable, and Generalizable",
  author = "Connor Brennan, Adeeti Aggarwal, Rui Pei, David Sussillo, Alex Proekt",
  journal = "Nature Neuroscience",
  number = " ",
  cites = 0,
  year = "submitted",
  cid = NA,
  pubid = NA
  ) %>% 
  # add_row(
  #   title = "Using the right tool for the job: understanding the difference between unsupervised and supervised analyses of multivariate ecological data",
  #   author = "ER Scott, EE Crone",
  #   journal = "Oecologia",
  #   number = " ",
  #   cites = 0,
  #   year = "in review",
  #   cid = NA,
  #   pubid = NA
  # ) %>% 
  arrange(desc(year)) %>%
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = journal
  )
# bibliography_entries(here("My Publications.bib"), title = NULL)

```

# Research Experience

```{r research}
jobs %>% 
  filter(Tag == "research") %>% 
  # arrange(desc(Start)) %>%
  arrange(desc(End)) %>% 
  detailed_entries(
    what = What,
    when = When,
    with = With,
    where = Where,
    why = Why,
    .protect = FALSE
  )
```

<!--# Teaching Interests
A sentence or two about the sorts of courses I'd like to teach.  Tailor to each job application
-->

# Teaching Experience

```{r}
jobs %>%
  filter(Tag == "teaching", year(Start) > 2005) %>%
  arrange(desc(Start)) %>% 
  detailed_entries(
    what = What,
    when = When,
    with = With,
    where = Where,
    why = Why, .protect = FALSE
  )
```

```{r}
## Guest Lectures
# presentations %>% 
#   filter(Tag %in% c("lecture")) %>% 
#   arrange(desc(When)) %>% 
#   detailed_entries(what = Title,
#                    when = glue("{month(When, label = TRUE)} {year(When)}") %>% as.character(),
#                    with = Conference,
#                    where = Location,
#                    why = Award)
```



# Grants

```{r}
awards %>%
  filter(tag == "grant") %>%
  detailed_entries(what = award, when = glue("{month(date, label = TRUE)} {year(date)}"),
                   why = amount) %>% 
  mutate_all(as.character)
  #        when = as.character(when),
  #        where = as.character(where))
```




```{r}
# # Awards and Honors
# awards %>% 
#   filter(!tag %in% c("failed", "travel", "grant")) %>% 
#   brief_entries(what = award, when = glue("{month(date, label = TRUE)} {year(date)}"), with = with)
```


```{r eval = FALSE}
## Software
# 
# df <- tribble(~what, ~when, ~with, ~where, ~why,
#               "webchem: retrieve chemical information from the web",
#               2020,
#               "E Szöcs, D Muench, J Ranke, ER Scott, J Stanstrup, R Allaway, Tamas Stirling",
#               "https://cran.r-project.org/web/packages/webchem/",
#               "Contributor and maintainer",
#               
#               "holodeck: A tidy interface for simulating multivariate data",
#               2018,
#               "ER Scott",
#               "https://cran.r-project.org/web/packages/holodeck/",
#               "Author and maintainer",
#               
#               "bumbl: Tools for modeling bumblebee colony growth",
#               2019,
#               "ER Scott, E Crone",
#               "https://github.com/Aariq/bumbl",
#               "Author and maintainer"
#               
#               )
# 
# df %>% 
#   arrange(desc(when)) %>% 
#   detailed_entries(what = what, when = when, with = with, where = where, why = why)
```


# Presentations

## Research Talks

```{r}
presentations %>% 
  filter(Tag %in% c("talk", "invited")) %>% 
  arrange(desc(When)) %>% 
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}"),
                   with = Conference,
                   where = Location,
                   why = Award,
                   .protect = FALSE)
```

## Posters

```{r}
presentations %>% 
  filter(Tag == "poster") %>% 
  arrange(desc(When)) %>% 
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}"),
                   with = Conference,
                   where = Location,
                   why = Award,
                   .protect = FALSE)
```


# Industry experience

```{r}
jobs %>%
  filter(Tag == "industry") %>%
  detailed_entries(
    what = What,
    when = When,
    with = With,
    where = Where,
    why = Why
  )
```

```{r}
# # Outreach
# outreach %>%
#   arrange(desc(sortdate)) %>%
#   detailed_entries(when = When,
#                    what = Title,
#                    with = Organization,
#                    where = Location,
#                    why = Description)
```


```{r}
# # Service
# 
# **Manuscript Reviews**
# #set this up to pull from publoons some day.
```







```{r}
# \pagebreak
## Presented Workshops
# presentations %>% 
#   filter(Tag == "workshop") %>% 
#   arrange(desc(When)) %>% 
#   detailed_entries(what = Title,
#                    when = glue("{month(When, label = TRUE)} {year(When)}"),
#                    with = Conference,
#                    where = Location,
#                    why = Award)
```



```{r}
# Professional Development
# development %>% 
#   brief_entries(
#     what = title,
#     when = glue("{month(date, label = TRUE)} {year(date)}"),
#     with = location
#   )
```